# example netlify.toml
[build]
command = "pnpm run build"
functions = "functions"
publish = "/public"

[[redirects]]
from = "/assessment-request"
to = "/connect"
status = 301
force = true

[[redirects]]
from = "/assessment-request/*"
to = "/connect"
status = 301
force = true
## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
[dev]
command = "pnpm run start" # Command to start your dev server
# port = 8000 # Port that the dev server will be listening on
publish = "/public" # Folder with the static content for _redirect file
# more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
